spring:
  application:
    name: aqjz_user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://8.140.108.235:3306/test
    username: root
    password: root
server:
  port: 8001


mybatis:
  mapperLocations: classpath:mapper/*.xml  # 装配mapper
  type-aliases-package: com.jz.aqjz.entities  # 所有Entity别名类所在包

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:8080
        allowed-methods: GET,POST
